import { AppShell, PageHeader } from "@/components/layout/AppShell";
import { ExportCard } from "@/components/reports/ExportCard";
import { PdfPreviewMock } from "@/components/reports/PdfPreviewMock";
import { Button } from "@/components/ui/button";
import { MOCK_EXPORTS } from "@/lib/mockData";
import { toast } from "sonner";

export default function ReportsExport() {
  return (
    <AppShell>
      <PageHeader
        eyebrow="Reports & Export"
        title="Reports & Export"
        description="Export clean watch schedules for the bridge, crew mess, department heads, or internal records."
      />
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <ExportCard
          title="Bridge Version"
          description="Full vessel watch schedule with all departments."
          variant="bridge"
        />
        <ExportCard
          title="Crew Mess Version"
          description="Simple crew-facing rota."
          variant="mess"
        />
        <ExportCard
          title="Department Version"
          description="Deck, Interior, or Engineering schedule."
          variant="department"
        />
        <ExportCard
          title="Compliance-Support Version"
          description="Includes rest-hour aware warnings, generated date, and version history."
          variant="compliance"
        />
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-2">
        <PdfPreviewMock />
        <div className="panel overflow-x-auto">
          <div className="flex items-center justify-between border-b border-border px-5 py-3">
            <div className="text-[11px] font-medium uppercase tracking-[0.16em] text-muted-foreground">
              Export history
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={() => toast("CSV export placeholder — backend connection required.")}
            >
              CSV export
            </Button>
          </div>
          <table className="w-full text-sm">
            <thead className="border-b border-border text-[11px] uppercase tracking-wider text-muted-foreground">
              <tr>
                <th className="px-5 py-3 text-left font-medium">Version</th>
                <th className="px-5 py-3 text-left font-medium">Date generated</th>
                <th className="px-5 py-3 text-left font-medium">Type</th>
                <th className="px-5 py-3 text-left font-medium">Generated by</th>
                <th className="px-5 py-3 text-left font-medium">Status</th>
                <th className="px-5 py-3 text-right font-medium">Download</th>
              </tr>
            </thead>
            <tbody>
              {MOCK_EXPORTS.map((e) => (
                <tr key={e.id} className="border-b border-border/60 last:border-0">
                  <td className="px-5 py-2 font-mono text-muted-foreground">v{e.version}</td>
                  <td className="px-5 py-2 font-mono text-[11px] text-muted-foreground">
                    {e.at.slice(0, 16).replace("T", " ")}
                  </td>
                  <td className="px-5 py-2">{e.variant}</td>
                  <td className="px-5 py-2 text-muted-foreground">Captain James Carter</td>
                  <td className="px-5 py-2 text-muted-foreground">Ready</td>
                  <td className="px-5 py-2 text-right">
                    <button
                      className="text-xs text-muted-foreground underline-offset-4 hover:text-foreground hover:underline"
                      onClick={() => toast("Download placeholder — backend connection required.")}
                    >
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </AppShell>
  );
}
